#!/bin/sh

[ -z $LISTEN_FDS -o $LISTEN_FDS -ne 1 ] && exit 1

mkdir -p /run/github-mirror

(
    while read -u 3 repository; do
       (cd "$repository"; /git/bin/post-receive-mirror-github) &
    done
) &

echo $! > /run/github-mirror/pid
